/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package delivery.king.hobanwoo.jpa;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {

    }
}
